CREATE OR REPLACE FUNCTION LM_ERROR 
(
  ERR_CODE IN VARCHAR2  
, PARAM1 IN VARCHAR2 := null
, PARAM2 IN VARCHAR2 := null 
, PARAM3 IN VARCHAR2 := null 
, PARAM4 IN VARCHAR2 := null 
, PARAM5 IN VARCHAR2 := null
) RETURN VARCHAR2 AS 
  ERROR_TEXT VARCHAR(4096);
BEGIN

  -- attempt a lookup
  SELECT ERROR_DESC INTO ERROR_TEXT FROM SIEBEL.CX_FINT_ERROR
   WHERE ERROR_CD = ERR_CODE;
  
  IF ERROR_TEXT IS NULL THEN
    RETURN 'Unknown error for code: '||ERR_CODE;
  ELSIF PARAM1 IS NULL THEN
    NULL; -- no parameters
  ELSIF PARAM2 IS NULL THEN
    SELECT REPLACE(ERROR_DESC,'%1',PARAM1) INTO ERROR_TEXT FROM SIEBEL.CX_FINT_ERROR
     WHERE ERROR_CD = ERR_CODE;
  ELSIF PARAM3 IS NULL THEN
    SELECT REPLACE(REPLACE(ERROR_DESC,'%1',PARAM1), '%2', PARAM2) INTO ERROR_TEXT FROM SIEBEL.CX_FINT_ERROR
     WHERE ERROR_CD = ERR_CODE;
  ELSIF PARAM4 IS NULL THEN
    SELECT REPLACE(REPLACE(REPLACE(ERROR_DESC,'%1',PARAM1), '%2', PARAM2),'%3',PARAM3) INTO ERROR_TEXT FROM SIEBEL.CX_FINT_ERROR
     WHERE ERROR_CD = ERR_CODE;
  ELSIF PARAM5 IS NULL THEN
    SELECT REPLACE(REPLACE(REPLACE(REPLACE(ERROR_DESC,'%1',PARAM1), '%2', PARAM2),'%3',PARAM3),'%4',PARAM4) INTO ERROR_TEXT FROM SIEBEL.CX_FINT_ERROR
     WHERE ERROR_CD = ERR_CODE;
  ELSE
    SELECT REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ERROR_DESC,'%1',PARAM1), '%2', PARAM2),'%3',PARAM3),'%4',PARAM4),'%5') INTO ERROR_TEXT FROM SIEBEL.CX_FINT_ERROR
     WHERE ERROR_CD = ERR_CODE;
  END IF;
  
  IF LENGTH(ERROR_TEXT) > 250 THEN
    ERROR_TEXT := SUBSTR(ERROR_TEXT,1,250);
  END IF;
  
  RETURN ERROR_TEXT;  
END LM_ERROR;

