--------------------------------------------------------
--  File created - Monday-August-27-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EIM_LOY_TXN
--------------------------------------------------------

  CREATE TABLE "POR"."EIM_LOY_TXN" 
   (	"ROW_ID" VARCHAR2(15 CHAR), 
	"CREATED" DATE DEFAULT sysdate, 
	"CREATED_BY" VARCHAR2(15 CHAR), 
	"LAST_UPD" DATE DEFAULT sysdate, 
	"LAST_UPD_BY" VARCHAR2(15 CHAR), 
	"MODIFICATION_NUM" NUMBER(10,0) DEFAULT 0, 
	"CONFLICT_ID" VARCHAR2(15 CHAR) DEFAULT '0', 
	"IF_ROW_BATCH_NUM" NUMBER(15,0) DEFAULT 0, 
	"IF_ROW_STAT" VARCHAR2(30 CHAR), 
	"TXN_NUM" VARCHAR2(30 CHAR), 
	"ACRLPRTNRPTDEBITQT" NUMBER(22,7), 
	"ACRLQUALIFYTYPEFLG" CHAR(1 CHAR), 
	"ACRL_ACCRUED_VALUE" NUMBER(22,7), 
	"ACRL_EFFECTIVE_TS" DATE, 
	"ACRL_EXPIRATION_TS" DATE, 
	"ACRL_PROCESS_TS" DATE, 
	"ACRL_REPAID_FLG" CHAR(1 CHAR), 
	"ACRL_USED_VALUE" NUMBER(22,7), 
	"ACTIVITY_DAY" NUMBER(10,0), 
	"ACTIVITY_HOUR" NUMBER(10,0), 
	"ADJ_LIST_PRI" NUMBER(22,7), 
	"AMT_VAL" NUMBER(22,7), 
	"APPROVE_DT" DATE, 
	"BID_FLG" CHAR(1 CHAR), 
	"BOOKING_DT" DATE, 
	"BULK_SEQ_NUM" NUMBER(10,0), 
	"CURCY_EXCH_DT" DATE, 
	"DB_LAST_UPD" DATE, 
	"END_DT" DATE, 
	"EXPIRE_IN_DAYS" NUMBER(10,0), 
	"EXTERNAL_FLG" CHAR(1 CHAR), 
	"IF_ROW_STAT_NUM" NUMBER(10,0), 
	"INTERNAL_FLIGHT_DT" DATE, 
	"ITM_SEQ_NUM" NUMBER(10,0), 
	"LOAN_BALANCE" NUMBER(22,7), 
	"LOAN_REPAYMENT_DT" DATE, 
	"NUM_POINTS" NUMBER(22,7), 
	"OPTY_COST" NUMBER(22,7), 
	"ORDER_NUM" NUMBER(10,0), 
	"ORDER_QTY" NUMBER(22,7), 
	"ORIGORDORDITMLNNU2" NUMBER(22,7), 
	"ORIGORDORDITMLNNUM" NUMBER(10,0), 
	"ORIGORDORDITMORDRE" NUMBER(22,7), 
	"ORIG_AMOUNT" NUMBER(22,7), 
	"ORIG_POINTS" NUMBER(22,7), 
	"ORIG_REV_NUM" NUMBER(22,7), 
	"OVR_DUP_CHECK_FLG" CHAR(1 CHAR), 
	"OVR_PRI_FLAG" CHAR(1 CHAR), 
	"PERSON_CON_PRIVFLG" CHAR(1 CHAR), 
	"POST_DT" DATE, 
	"PROCESS_DT" DATE, 
	"PTNR_PROC_DT" DATE, 
	"QUAL_FLG" CHAR(1 CHAR), 
	"RDM_QTY" NUMBER(22,7), 
	"REFUND_PCT" NUMBER(22,7), 
	"START_DT" DATE, 
	"SUBMIT_DT" DATE, 
	"TAX_AMT" NUMBER(22,7), 
	"TOTAL_LINES" NUMBER(10,0), 
	"TRVL_DISTANCE" NUMBER(22,7), 
	"TXN_DT" DATE, 
	"T_LOYBCKTTX__EXS" CHAR(1 CHAR), 
	"T_LOYBCKTTX__STA" NUMBER(10,0), 
	"T_LOYBCKTTX__UNQ" CHAR(1 CHAR), 
	"T_LOYSR_TXN__EXS" CHAR(1 CHAR), 
	"T_LOYSR_TXN__STA" NUMBER(10,0), 
	"T_LOYSR_TXN__UNQ" CHAR(1 CHAR), 
	"T_LOYTXNITE__EXS" CHAR(1 CHAR), 
	"T_LOYTXNITE__STA" NUMBER(10,0), 
	"T_LOYTXNITE__UNQ" CHAR(1 CHAR), 
	"T_LOYTXN_BU__EXS" CHAR(1 CHAR), 
	"T_LOYTXN_BU__STA" NUMBER(10,0), 
	"T_LOYTXN_BU__UNQ" CHAR(1 CHAR), 
	"T_LOY_ACRLDTL__EXS" CHAR(1 CHAR), 
	"T_LOY_ACRLDTL__STA" NUMBER(10,0), 
	"T_LOY_ACRLDTL__UNQ" CHAR(1 CHAR), 
	"T_LOY_TXN__EXS" CHAR(1 CHAR), 
	"T_LOY_TXN__STA" NUMBER(10,0), 
	"T_LOY_TXN__UNQ" CHAR(1 CHAR), 
	"UNACC_MINOR_FLG" CHAR(1 CHAR), 
	"VOUCHER_QTY" NUMBER(10,0), 
	"ACCRPROGRAMID_BIID" VARCHAR2(15 CHAR), 
	"ACCRPROGRAMID_BUID" VARCHAR2(100 CHAR), 
	"ACCR_ACRL_PROGNAME" VARCHAR2(50 CHAR), 
	"ACCR_ACRL_PROG_BI" VARCHAR2(15 CHAR), 
	"ACCR_ACRL_PROG_BU" VARCHAR2(100 CHAR), 
	"ACRL_ACRL_ITEM_NUM" VARCHAR2(30 CHAR), 
	"ACRL_ACT_ROW_ID" VARCHAR2(15 CHAR), 
	"ACRL_ATTRIBATTRTYP" VARCHAR2(30 CHAR), 
	"ACRL_ATTRIBINTERNA" VARCHAR2(75 CHAR), 
	"ACRL_ATTRIBOBJECTC" VARCHAR2(30 CHAR), 
	"ACRL_ATTRIBPRG_BI" VARCHAR2(15 CHAR), 
	"ACRL_ATTRIBPRG_BU" VARCHAR2(100 CHAR), 
	"ACRL_ATTRIBPROGNAM" VARCHAR2(50 CHAR), 
	"ACRL_ATTRIBPROG_BI" VARCHAR2(15 CHAR), 
	"ACRL_ATTRIBPROG_BU" VARCHAR2(100 CHAR), 
	"ACRL_ATTRIBPROMONA" VARCHAR2(50 CHAR), 
	"ACRL_ATTRIBPROMOPR" VARCHAR2(50 CHAR), 
	"ACRL_ATTRIBPROM_BI" VARCHAR2(15 CHAR), 
	"ACRL_ATTRIBPROM_BU" VARCHAR2(100 CHAR), 
	"ACRL_COMMENTS" VARCHAR2(250 CHAR), 
	"ACRL_ITEM_LINE_NUM" VARCHAR2(30 CHAR), 
	"ACRL_PROMOBUCKETUI" VARCHAR2(30 CHAR), 
	"ACRL_PROMOPROGNAME" VARCHAR2(50 CHAR), 
	"ACRL_PROMO_BI" VARCHAR2(15 CHAR), 
	"ACRL_PROMO_BU" VARCHAR2(100 CHAR), 
	"ACRL_PROMO_NAME" VARCHAR2(50 CHAR), 
	"ACRL_PROMO_PROG_BI" VARCHAR2(15 CHAR), 
	"ACRL_PROMO_PROG_BU" VARCHAR2(100 CHAR), 
	"ACRL_PTBLK_ROW_ID" VARCHAR2(15 CHAR), 
	"ACRL_PTSUBPROGRAMN" VARCHAR2(50 CHAR), 
	"ACRL_PTSUBPROGR_BI" VARCHAR2(15 CHAR), 
	"ACRL_PTSUBPROGR_BU" VARCHAR2(100 CHAR), 
	"ACRL_PT_SUB_NAME" VARCHAR2(50 CHAR), 
	"ACRL_STATUS_CODE" VARCHAR2(30 CHAR), 
	"ACRL_TYPE_CD" VARCHAR2(30 CHAR), 
	"APPROVELOGINDOMAIN" VARCHAR2(50 CHAR), 
	"APPROVE_LOGIN" VARCHAR2(50 CHAR), 
	"BCKT_PROMOBUCKETUI" VARCHAR2(30 CHAR), 
	"BOOK_CLASS_CD" VARCHAR2(30 CHAR), 
	"BULK_BLKADPROGNAME" VARCHAR2(50 CHAR), 
	"BULK_BLKAD_PROG_BI" VARCHAR2(15 CHAR), 
	"BULK_BLKAD_PROG_BU" VARCHAR2(100 CHAR), 
	"CANCELLED_TXN_BI" VARCHAR2(15 CHAR), 
	"CANCELLED_TXN_BU" VARCHAR2(100 CHAR), 
	"CANCELLED_TXN_NUM" VARCHAR2(30 CHAR), 
	"CANC_REASON_CD" VARCHAR2(30 CHAR), 
	"CHILD_TXN_BI" VARCHAR2(15 CHAR), 
	"CHILD_TXN_BU" VARCHAR2(100 CHAR), 
	"CHILD_TXN_NUM" VARCHAR2(30 CHAR), 
	"COMMENTS" VARCHAR2(250 CHAR), 
	"CORP_REF_NUM" VARCHAR2(15 CHAR), 
	"CURCY_CD" VARCHAR2(20 CHAR), 
	"DB_LAST_UPD_SRC" VARCHAR2(50 CHAR), 
	"DEST_AIRPORT_CD" VARCHAR2(30 CHAR), 
	"DEST_CITY_CD" VARCHAR2(30 CHAR), 
	"DEST_ZONE_CD" VARCHAR2(30 CHAR), 
	"DOC_NUM" VARCHAR2(30 CHAR), 
	"ENROL_PROG_BI" VARCHAR2(15 CHAR), 
	"ENROL_PROG_BU" VARCHAR2(100 CHAR), 
	"ENROL_PROG_NAME" VARCHAR2(50 CHAR), 
	"ENROL_PROMO_BI" VARCHAR2(15 CHAR), 
	"ENROL_PROMO_BU" VARCHAR2(100 CHAR), 
	"ENROL_PROMO_NAME" VARCHAR2(50 CHAR), 
	"EXT_RES_NUM" VARCHAR2(250 CHAR), 
	"FARE_BASIS" VARCHAR2(30 CHAR), 
	"FARE_BASIS_CD" VARCHAR2(30 CHAR), 
	"FARE_TYPE_CD" VARCHAR2(30 CHAR), 
	"FLT_NUM" VARCHAR2(30 CHAR), 
	"FLT_TYPE_CD" VARCHAR2(30 CHAR), 
	"GDS_REC_LOCATOR" VARCHAR2(30 CHAR), 
	"IF_ROW_MERGE_ID" VARCHAR2(15 CHAR), 
	"INCENTIV_CHOICE" VARCHAR2(30 CHAR), 
	"INTEGRATION_ID" VARCHAR2(30 CHAR), 
	"INTERNAL_DEST" VARCHAR2(15 CHAR), 
	"INTERNAL_ORIGIN" VARCHAR2(15 CHAR), 
	"ITEM_NUM" VARCHAR2(30 CHAR), 
	"ITM_PARTNERACCNTLO" VARCHAR2(50 CHAR), 
	"ITM_PARTNERACCNTNA" VARCHAR2(100 CHAR), 
	"ITM_PARTNERACCN_BI" VARCHAR2(15 CHAR), 
	"ITM_PARTNERACCN_BU" VARCHAR2(100 CHAR), 
	"ITM_PNR_NUM" VARCHAR2(50 CHAR), 
	"ITM_PRTNRPRODVENLO" VARCHAR2(50 CHAR), 
	"ITM_PRTNRPRODVENNA" VARCHAR2(100 CHAR), 
	"ITM_PRTNRPRODVE_BI" VARCHAR2(15 CHAR), 
	"ITM_PRTNRPRODVE_BU" VARCHAR2(100 CHAR), 
	"ITM_PRTNR_PRODNAME" VARCHAR2(100 CHAR), 
	"ITM_PRTNR_PROD_BI" VARCHAR2(15 CHAR), 
	"ITM_PRTNR_PROD_BU" VARCHAR2(100 CHAR), 
	"LOCATION_CD" VARCHAR2(30 CHAR), 
	"LOC_NAME" VARCHAR2(100 CHAR), 
	"LOC_ORG_BI" VARCHAR2(15 CHAR), 
	"LOC_ORG_BU" VARCHAR2(100 CHAR), 
	"LOC_ORG_LOC" VARCHAR2(50 CHAR), 
	"LOC_ORG_NAME" VARCHAR2(100 CHAR), 
	"LT_ACCR_RULE_NAME" VARCHAR2(75 CHAR), 
	"MEMBER_MEM_BI" VARCHAR2(15 CHAR), 
	"MEMBER_MEM_BU" VARCHAR2(100 CHAR), 
	"MEMBER_MEM_NUM" VARCHAR2(30 CHAR), 
	"MEMBER_PROG_BI" VARCHAR2(15 CHAR), 
	"MEMBER_PROG_BU" VARCHAR2(100 CHAR), 
	"MEMBER_PROG_NAME" VARCHAR2(50 CHAR), 
	"MKTG_FLT_NUM" VARCHAR2(30 CHAR), 
	"OPER_ACCNT_BI" VARCHAR2(15 CHAR), 
	"OPER_ACCNT_BU" VARCHAR2(100 CHAR), 
	"OPER_ACCNT_LOC" VARCHAR2(50 CHAR), 
	"OPER_ACCNT_NAME" VARCHAR2(100 CHAR), 
	"OPER_FLT_NUM" VARCHAR2(30 CHAR), 
	"ORIGIN_CITY_CD" VARCHAR2(30 CHAR), 
	"ORIGORDORDITMORDNU" VARCHAR2(30 CHAR), 
	"ORIGORDORDITMORDTY" VARCHAR2(50 CHAR), 
	"ORIGORDORDITMOR_BI" VARCHAR2(15 CHAR), 
	"ORIGORDORDITMOR_BU" VARCHAR2(100 CHAR), 
	"ORIG_ACRL_TXN_BI" VARCHAR2(15 CHAR), 
	"ORIG_ACRL_TXN_BU" VARCHAR2(100 CHAR), 
	"ORIG_ACRL_TXN_NUM" VARCHAR2(30 CHAR), 
	"ORIG_AIRPORT_CD" VARCHAR2(30 CHAR), 
	"ORIG_ORDER_BI" VARCHAR2(15 CHAR), 
	"ORIG_ORDER_BU" VARCHAR2(100 CHAR), 
	"ORIG_ORDER_NUM" VARCHAR2(30 CHAR), 
	"ORIG_ORDER_TYPE" VARCHAR2(50 CHAR), 
	"ORIG_ZONE_CD" VARCHAR2(30 CHAR), 
	"OWNER_LOGIN" VARCHAR2(50 CHAR), 
	"OWNER_LOGIN_DOMAIN" VARCHAR2(50 CHAR), 
	"PACKAGE_CD" VARCHAR2(30 CHAR), 
	"PARTITION_NAME" VARCHAR2(30 CHAR), 
	"PARTNER_ACCNT_BI" VARCHAR2(15 CHAR), 
	"PARTNER_ACCNT_BU" VARCHAR2(100 CHAR), 
	"PARTNER_ACCNT_LOC" VARCHAR2(50 CHAR), 
	"PARTNER_ACCNT_NAME" VARCHAR2(100 CHAR), 
	"PAR_TXN_NUM" VARCHAR2(30 CHAR), 
	"PAR_TXN_TXN_BI" VARCHAR2(15 CHAR), 
	"PAR_TXN_TXN_BU" VARCHAR2(100 CHAR), 
	"PERIOD_DUR_CD" VARCHAR2(30 CHAR), 
	"PERIOD_TYPE_CD" VARCHAR2(30 CHAR), 
	"PERSON_CON_BI" VARCHAR2(15 CHAR), 
	"PERSON_CON_BU" VARCHAR2(100 CHAR), 
	"PERSON_UID" VARCHAR2(100 CHAR), 
	"PNR_NAME" VARCHAR2(50 CHAR), 
	"POINTPROMOPROGNAME" VARCHAR2(50 CHAR), 
	"POINT_ATTR_TYPE_CD" VARCHAR2(30 CHAR), 
	"POINT_INTERNALNAME" VARCHAR2(75 CHAR), 
	"POINT_OBJECT_CD" VARCHAR2(30 CHAR), 
	"POINT_PROG_BI" VARCHAR2(15 CHAR), 
	"POINT_PROG_BU" VARCHAR2(100 CHAR), 
	"POINT_PROG_NAME" VARCHAR2(50 CHAR), 
	"POINT_PROMOPROG_BI" VARCHAR2(15 CHAR), 
	"POINT_PROMOPROG_BU" VARCHAR2(100 CHAR), 
	"POINT_PROMO_BI" VARCHAR2(15 CHAR), 
	"POINT_PROMO_BU" VARCHAR2(100 CHAR), 
	"POINT_PROMO_NAME" VARCHAR2(50 CHAR), 
	"PROCESSING_COMMENT" VARCHAR2(1000 CHAR), 
	"PROCESSING_LOG" VARCHAR2(1000 CHAR), 
	"PROD_BI" VARCHAR2(15 CHAR), 
	"PROD_BU" VARCHAR2(100 CHAR), 
	"PROD_NAME" VARCHAR2(100 CHAR), 
	"PROD_VEN_BI" VARCHAR2(15 CHAR), 
	"PROD_VEN_BU" VARCHAR2(100 CHAR), 
	"PROD_VEN_LOC" VARCHAR2(50 CHAR), 
	"PROD_VEN_NAME" VARCHAR2(100 CHAR), 
	"PROG_BI" VARCHAR2(15 CHAR), 
	"PROG_BU" VARCHAR2(100 CHAR), 
	"PROG_NAME" VARCHAR2(50 CHAR), 
	"PTNR_LOGIN" VARCHAR2(50 CHAR), 
	"PTNR_LOGIN_DOMAIN" VARCHAR2(50 CHAR), 
	"PTNR_STATUS_CD" VARCHAR2(30 CHAR), 
	"PYMT_TYPE_CD" VARCHAR2(30 CHAR), 
	"RDM_ITEM_NUM" VARCHAR2(30 CHAR), 
	"RDM_QTY_UOM_CD" VARCHAR2(30 CHAR), 
	"REASON_CD" VARCHAR2(30 CHAR), 
	"REFUND_BASIS_CD" VARCHAR2(30 CHAR), 
	"RFND_OVRD_CMNTS" VARCHAR2(250 CHAR), 
	"RFND_OVRD_RSN_CD" VARCHAR2(30 CHAR), 
	"SOURCE_CD" VARCHAR2(30 CHAR), 
	"SR_BI" VARCHAR2(15 CHAR), 
	"SR_BU" VARCHAR2(100 CHAR), 
	"SR_NUM" VARCHAR2(64 CHAR), 
	"STATUS_CD" VARCHAR2(30 CHAR), 
	"SUBMIT_LOGIN" VARCHAR2(50 CHAR), 
	"SUBMIT_LOGINDOMAIN" VARCHAR2(50 CHAR), 
	"SUB_STATUS_CD" VARCHAR2(30 CHAR), 
	"SUB_TYPE_CD" VARCHAR2(30 CHAR), 
	"TICKET_NUM" VARCHAR2(30 CHAR), 
	"TO_MEM_NUM" VARCHAR2(30 CHAR), 
	"TRANSFER_MEM_BI" VARCHAR2(15 CHAR), 
	"TRANSFER_MEM_BU" VARCHAR2(100 CHAR), 
	"TRANSFER_MEM_NUM" VARCHAR2(30 CHAR), 
	"TRANSFER_PROG_BI" VARCHAR2(15 CHAR), 
	"TRANSFER_PROG_BU" VARCHAR2(100 CHAR), 
	"TRANSFER_PROG_NAME" VARCHAR2(50 CHAR), 
	"TRANSFER_TXN_BI" VARCHAR2(15 CHAR), 
	"TRANSFER_TXN_BU" VARCHAR2(100 CHAR), 
	"TRANSFER_TXN_NUM" VARCHAR2(30 CHAR), 
	"TRV_CLASS_CD" VARCHAR2(30 CHAR), 
	"TXN_BI" VARCHAR2(15 CHAR), 
	"TXN_BU" VARCHAR2(100 CHAR), 
	"TXN_CHANNEL_CD" VARCHAR2(30 CHAR), 
	"TXN_SOURCE_CD" VARCHAR2(30 CHAR), 
	"TYPE_CD" VARCHAR2(30 CHAR), 
	"T_ACRLATTRIBDEFNID" VARCHAR2(15 CHAR), 
	"T_ACRLPROMOBUCKETI" VARCHAR2(15 CHAR), 
	"T_ACRL_ACRL_ITM_ID" VARCHAR2(15 CHAR), 
	"T_ACRL_ACTION_ID" VARCHAR2(15 CHAR), 
	"T_ACRL_POINTBLKID" VARCHAR2(15 CHAR), 
	"T_ACRL_PROMO_ID" VARCHAR2(15 CHAR), 
	"T_ACRL_PTSUBTYPEID" VARCHAR2(15 CHAR), 
	"T_ACRL_TXN_ID" VARCHAR2(15 CHAR), 
	"T_DELETED_ROW_ID" VARCHAR2(15 CHAR), 
	"T_EXPORTED_ROW_ID" VARCHAR2(15 CHAR), 
	"T_LOYBCKTTX_PROMOB" VARCHAR2(15 CHAR), 
	"T_LOYBCKTTX_TXN_ID" VARCHAR2(15 CHAR), 
	"T_LOYBCKTTX__RID" VARCHAR2(15 CHAR), 
	"T_LOYSR_TXN_SRVREQ" VARCHAR2(15 CHAR), 
	"T_LOYSR_TXN_TXN_ID" VARCHAR2(15 CHAR), 
	"T_LOYSR_TXN__RID" VARCHAR2(15 CHAR), 
	"T_LOYTXNITE_PARTNE" VARCHAR2(15 CHAR), 
	"T_LOYTXNITE_PRTNRP" VARCHAR2(15 CHAR), 
	"T_LOYTXNITE_TXN_ID" VARCHAR2(15 CHAR), 
	"T_LOYTXNITE__RID" VARCHAR2(15 CHAR), 
	"T_LOYTXN_BU_BU_ID" VARCHAR2(15 CHAR), 
	"T_LOYTXN_BU_TXN_ID" VARCHAR2(15 CHAR), 
	"T_LOYTXN_BU__RID" VARCHAR2(15 CHAR), 
	"T_LOY_ACRLDTL__RID" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_ACCRRU" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_APPROV" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_BULKRE" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_BU_ID" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_CANCEL" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_CHILDT" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_ENROLP" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_LOC_ID" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_MEMBER" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_OPERCA" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_ORIGAC" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_ORIGOR" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_ORIGOR1" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_OWNERI" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_PARTNE" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_PARTXN" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_PERSON" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_POINTT" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_PRODID" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_PROGID" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_PTNRUS" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_RDMITM" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_SUBMIT" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_TRANSF" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_TRANSF1" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_VOUCHE" VARCHAR2(15 CHAR), 
	"T_LOY_TXN_VOUCHE1" VARCHAR2(15 CHAR), 
	"T_LOY_TXN__RID" VARCHAR2(15 CHAR), 
	"T_MERGED_ROW_ID" VARCHAR2(15 CHAR), 
	"VAL_STATUS_CD" VARCHAR2(30 CHAR), 
	"VCHRTP_PRDVEN_BI" VARCHAR2(15 CHAR), 
	"VCHRTP_PRDVEN_BU" VARCHAR2(100 CHAR), 
	"VCHRTP_PRDVEN_LOC" VARCHAR2(50 CHAR), 
	"VCHRTP_PRDVEN_NAME" VARCHAR2(100 CHAR), 
	"VCHRTP_PRD_BI" VARCHAR2(15 CHAR), 
	"VCHRTP_PRD_BU" VARCHAR2(100 CHAR), 
	"VCHRTP_PRD_NAME" VARCHAR2(100 CHAR), 
	"VIS_BI" VARCHAR2(15 CHAR), 
	"VIS_BU" VARCHAR2(100 CHAR), 
	"VOUCHERPRODVENNAME" VARCHAR2(100 CHAR), 
	"VOUCHER_NUM" VARCHAR2(30 CHAR), 
	"VOUCHER_PRODVENLOC" VARCHAR2(50 CHAR), 
	"VOUCHER_PRODVEN_BI" VARCHAR2(15 CHAR), 
	"VOUCHER_PRODVEN_BU" VARCHAR2(100 CHAR), 
	"VOUCHER_PROD_BI" VARCHAR2(15 CHAR), 
	"VOUCHER_PROD_BU" VARCHAR2(100 CHAR), 
	"VOUCHER_PROD_NAME" VARCHAR2(100 CHAR), 
	"FILE_ID" VARCHAR2(30 BYTE), 
	"X_FILE_ID" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 20 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 12582912 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T11
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T11" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_LOYTXN_BU_TXN_ID", "T_LOYTXN_BU_BU_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T12
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T12" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_LOYTXNITE__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T13
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T13" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_LOYTXNITE_TXN_ID", "ITM_SEQ_NUM") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T14
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T14" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_ACRL_TXN_ID", "ACRL_ITEM_LINE_NUM") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T15
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T15" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_LOY_ACRLDTL__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_U1
--------------------------------------------------------

  CREATE UNIQUE INDEX "POR"."EIM_LOY_TXN_U1" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "ROW_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 983040 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T01
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T01" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_DELETED_ROW_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T02
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T02" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_MERGED_ROW_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T03
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T03" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_LOY_TXN__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T04
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T04" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "TXN_NUM", "T_LOY_TXN_BU_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T05
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T05" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "TXN_NUM", "TXN_BI") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T06
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T06" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_LOYBCKTTX__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T07
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T07" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_LOYBCKTTX_PROMOB", "T_LOYBCKTTX_TXN_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T08
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T08" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_LOYSR_TXN__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T09
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T09" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_LOYSR_TXN_SRVREQ", "T_LOYSR_TXN_TXN_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 786432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_TXN_T10
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_TXN_T10" ON "POR"."EIM_LOY_TXN" ("IF_ROW_BATCH_NUM", "T_LOYTXN_BU__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EIM_LOY_TXN
--------------------------------------------------------

  ALTER TABLE "POR"."EIM_LOY_TXN" MODIFY ("TXN_NUM" NOT NULL ENABLE);
  ALTER TABLE "POR"."EIM_LOY_TXN" MODIFY ("IF_ROW_STAT" NOT NULL ENABLE);
  ALTER TABLE "POR"."EIM_LOY_TXN" MODIFY ("IF_ROW_BATCH_NUM" NOT NULL ENABLE);
  ALTER TABLE "POR"."EIM_LOY_TXN" MODIFY ("ROW_ID" NOT NULL ENABLE);

