--------------------------------------------------------
--  File created - Monday-August-27-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EIM_LOY_MEMBER
--------------------------------------------------------

  CREATE TABLE "POR"."EIM_LOY_MEMBER" 
   (	"ROW_ID" VARCHAR2(15 CHAR), 
	"CREATED" DATE DEFAULT sysdate, 
	"CREATED_BY" VARCHAR2(15 CHAR), 
	"LAST_UPD" DATE DEFAULT sysdate, 
	"LAST_UPD_BY" VARCHAR2(15 CHAR), 
	"MODIFICATION_NUM" NUMBER(10,0) DEFAULT 0, 
	"CONFLICT_ID" VARCHAR2(15 CHAR) DEFAULT '0', 
	"IF_ROW_BATCH_NUM" NUMBER(15,0) DEFAULT 0, 
	"IF_ROW_STAT" VARCHAR2(30 CHAR), 
	"MEM_NUM" VARCHAR2(30 CHAR), 
	"ACCRUAL_START_DT" DATE, 
	"APPR_DT" DATE, 
	"CHILD_NUM" NUMBER(10,0), 
	"CON_PER_CONPRIVFLG" CHAR(1 CHAR), 
	"CON_PRIV_FLG" CHAR(1 CHAR), 
	"CRD_ACTIVE_FLG" CHAR(1 CHAR), 
	"CRD_EXP_DT" DATE, 
	"CRD_EXP_DT_ON_CARD" DATE, 
	"CRD_ISSUE_DT" DATE, 
	"CRD_REQUEST_DT" DATE, 
	"CRD_START_DT" DATE, 
	"CURCY_DT" DATE, 
	"DB_LAST_UPD" DATE, 
	"DISPLAY_SEQ" NUMBER(10,0), 
	"EXPIRY_DT" DATE, 
	"IF_ROW_STAT_NUM" NUMBER(10,0), 
	"LAST_ACCR_TXN_DT" DATE, 
	"LAST_RDM_TXN_DT" DATE, 
	"LAST_TXN_PROCED_DT" DATE, 
	"LFTM_PT_TYPE_A_VAL" NUMBER(22,7), 
	"LFTM_PT_TYPE_B_VAL" NUMBER(22,7), 
	"LFTM_PT_TYPE_C_VAL" NUMBER(22,7), 
	"LFTM_PT_TYPE_D_VAL" NUMBER(22,7), 
	"LFTM_PT_TYPE_E_VAL" NUMBER(22,7), 
	"LFTM_PT_TYPE_F_VAL" NUMBER(22,7), 
	"LFTM_PT_TYPE_G_VAL" NUMBER(22,7), 
	"LFTM_PT_TYPE_H_VAL" NUMBER(22,7), 
	"LOUNGE_BUY_END_DT" DATE, 
	"LOUNGE_BUY_ST_DT" DATE, 
	"LOUNGE_END_DT" DATE, 
	"LOUNGE_START_DT" DATE, 
	"LOY_LST_STMT_DT" DATE, 
	"LST_TIER_CHANGE_DT" DATE, 
	"MAX_POINT_LOAN" NUMBER(22,7), 
	"MEM_PR_CON" CHAR(1 CHAR), 
	"PARENT_FLG" CHAR(1 CHAR), 
	"PIN_NUM" NUMBER(11,0), 
	"POINT_TYPE_A_VAL" NUMBER(22,7), 
	"POINT_TYPE_B_VAL" NUMBER(22,7), 
	"POINT_TYPE_C_VAL" NUMBER(22,7), 
	"POINT_TYPE_D_VAL" NUMBER(22,7), 
	"POINT_TYPE_E_VAL" NUMBER(22,7), 
	"POINT_TYPE_F_VAL" NUMBER(22,7), 
	"POINT_TYPE_G_VAL" NUMBER(22,7), 
	"POINT_TYPE_H_VAL" NUMBER(22,7), 
	"PR_DOM_TIER" CHAR(1 CHAR), 
	"PR_POSTN" CHAR(1 CHAR), 
	"REC_PROM_FLG" CHAR(1 CHAR), 
	"REC_PTNR_PROM_FLG" CHAR(1 CHAR), 
	"START_DT" DATE, 
	"SUBMIT_DT" DATE, 
	"SUPPRESS_CALL_FLG" CHAR(1 CHAR), 
	"SUPPRESS_EMAIL_FLG" CHAR(1 CHAR), 
	"SUPPRESS_FAX_FLG" CHAR(1 CHAR), 
	"SUPPRESS_MAIL_FLG" CHAR(1 CHAR), 
	"SUPPRESS_SMS_FLG" CHAR(1 CHAR), 
	"TIERFUTRTIERSTAMPD" DATE, 
	"TIER_ACTIVE_FLG" CHAR(1 CHAR), 
	"TIER_APPROVED_DT" DATE, 
	"TIER_BULK_SEQ_NUM" NUMBER(10,0), 
	"TIER_END_DT" DATE, 
	"TIER_NEXT_ASSESSDT" DATE, 
	"TIER_ORIG_END_DT" DATE, 
	"TIER_OVERRIDE_DT" DATE, 
	"TIER_POINTTYPEAVAL" NUMBER(22,7), 
	"TIER_POINTTYPEBVAL" NUMBER(22,7), 
	"TIER_POINTTYPECVAL" NUMBER(22,7), 
	"TIER_POINTTYPEDVAL" NUMBER(22,7), 
	"TIER_POINTTYPEEVAL" NUMBER(22,7), 
	"TIER_POINTTYPEFVAL" NUMBER(22,7), 
	"TIER_POINTTYPEGVAL" NUMBER(22,7), 
	"TIER_POINTTYPEHVAL" NUMBER(22,7), 
	"TIER_PROCESSED_DT" DATE, 
	"TIER_QUAL_END_DT" DATE, 
	"TIER_QUAL_FLG" CHAR(1 CHAR), 
	"TIER_SEQ_NUM" NUMBER(10,0), 
	"TIER_START_DT" DATE, 
	"T_LOYATTRIB__EXS" CHAR(1 CHAR), 
	"T_LOYATTRIB__STA" NUMBER(10,0), 
	"T_LOYATTRIB__UNQ" CHAR(1 CHAR), 
	"T_LOYMEMBER__EXS" CHAR(1 CHAR), 
	"T_LOYMEMBER__STA" NUMBER(10,0), 
	"T_LOYMEMBER__UNQ" CHAR(1 CHAR), 
	"T_LOYMEMCON__EXS" CHAR(1 CHAR), 
	"T_LOYMEMCON__STA" NUMBER(10,0), 
	"T_LOYMEMCON__UNQ" CHAR(1 CHAR), 
	"T_LOYMEMPST__EXS" CHAR(1 CHAR), 
	"T_LOYMEMPST__STA" NUMBER(10,0), 
	"T_LOYMEMPST__UNQ" CHAR(1 CHAR), 
	"T_LOYMEMPTR__EXS" CHAR(1 CHAR), 
	"T_LOYMEMPTR__STA" NUMBER(10,0), 
	"T_LOYMEMPTR__UNQ" CHAR(1 CHAR), 
	"T_LOYMEMTIE__EXS" CHAR(1 CHAR), 
	"T_LOYMEMTIE__STA" NUMBER(10,0), 
	"T_LOYMEMTIE__UNQ" CHAR(1 CHAR), 
	"T_LOYMEM_BU__EXS" CHAR(1 CHAR), 
	"T_LOYMEM_BU__STA" NUMBER(10,0), 
	"T_LOYMEM_BU__UNQ" CHAR(1 CHAR), 
	"T_LOY_CARD__EXS" CHAR(1 CHAR), 
	"T_LOY_CARD__STA" NUMBER(10,0), 
	"T_LOY_CARD__UNQ" CHAR(1 CHAR), 
	"ACCNT_BI" VARCHAR2(15 CHAR), 
	"ACCNT_BU" VARCHAR2(100 CHAR), 
	"ACCNT_LOC" VARCHAR2(50 CHAR), 
	"ACCNT_NAME" VARCHAR2(100 CHAR), 
	"ACCRUAL_TOPROGNAME" VARCHAR2(50 CHAR), 
	"ACCRUAL_TO_MEM_BI" VARCHAR2(15 CHAR), 
	"ACCRUAL_TO_MEM_BU" VARCHAR2(100 CHAR), 
	"ACCRUAL_TO_MEM_NUM" VARCHAR2(30 CHAR), 
	"ACCRUAL_TO_PROG_BI" VARCHAR2(15 CHAR), 
	"ACCRUAL_TO_PROG_BU" VARCHAR2(100 CHAR), 
	"ACCRUAL_TYPE_CD" VARCHAR2(30 CHAR), 
	"APPR_BYLOGINDOMAIN" VARCHAR2(50 CHAR), 
	"APPR_BY_LOGIN" VARCHAR2(50 CHAR), 
	"ATR_ATTRIBPROMOPRO" VARCHAR2(50 CHAR), 
	"ATR_ATTR_TYPE_CD" VARCHAR2(30 CHAR), 
	"ATR_INTERNAL_NAME" VARCHAR2(75 CHAR), 
	"ATR_OBJECT_CD" VARCHAR2(30 CHAR), 
	"ATR_PROG_BI" VARCHAR2(15 CHAR), 
	"ATR_PROG_BU" VARCHAR2(100 CHAR), 
	"ATR_PROG_NAME" VARCHAR2(50 CHAR), 
	"ATR_PROMO_BI" VARCHAR2(15 CHAR), 
	"ATR_PROMO_BU" VARCHAR2(100 CHAR), 
	"ATR_PROMO_NAME" VARCHAR2(50 CHAR), 
	"ATR_PROMO_PROG_BI" VARCHAR2(15 CHAR), 
	"ATR_PROMO_PROG_BU" VARCHAR2(100 CHAR), 
	"ATR_VALUE" VARCHAR2(250 CHAR), 
	"CON_BI" VARCHAR2(15 CHAR), 
	"CON_BU" VARCHAR2(100 CHAR), 
	"CON_PERSON_UID" VARCHAR2(100 CHAR), 
	"CON_PER_CON_BI" VARCHAR2(15 CHAR), 
	"CON_PER_CON_BU" VARCHAR2(100 CHAR), 
	"CORP_MEM_NUM" VARCHAR2(15 CHAR), 
	"CRD_CARD_NUM" VARCHAR2(30 CHAR), 
	"CRD_CARD_TYPE_CD" VARCHAR2(30 CHAR), 
	"CRD_DESC_TEXT" VARCHAR2(250 CHAR), 
	"CRD_NAME_ON_CARD" VARCHAR2(50 CHAR), 
	"CRD_STATUS_CD" VARCHAR2(30 CHAR), 
	"CRD_TIER_CLS_NAME" VARCHAR2(30 CHAR), 
	"CRD_TIER_NAME" VARCHAR2(30 CHAR), 
	"CRD_TIER_PROG_BI" VARCHAR2(15 CHAR), 
	"CRD_TIER_PROG_BU" VARCHAR2(100 CHAR), 
	"CRD_TIER_PROG_NAME" VARCHAR2(50 CHAR), 
	"CURCY_CD" VARCHAR2(20 CHAR), 
	"DB_LAST_UPD_SRC" VARCHAR2(50 CHAR), 
	"DESC_TEXT" VARCHAR2(250 CHAR), 
	"GRP_NAME" VARCHAR2(100 CHAR), 
	"HOME_AIRPORT" VARCHAR2(30 CHAR), 
	"IF_ROW_MERGE_ID" VARCHAR2(15 CHAR), 
	"INCOMPLETE_FLIGHTS" VARCHAR2(1000 CHAR), 
	"LANG_ID" VARCHAR2(5 CHAR), 
	"LOUNGE_BUY_CD" VARCHAR2(30 CHAR), 
	"LOUNGE_CD" VARCHAR2(30 CHAR), 
	"LOUNGE_NUM" VARCHAR2(100 CHAR), 
	"LOY_MEMBER_BI" VARCHAR2(15 CHAR), 
	"LOY_MEMBER_BU" VARCHAR2(100 CHAR), 
	"LST_STMT_NUM" VARCHAR2(30 CHAR), 
	"MAXPOINTATTRTYPECD" VARCHAR2(30 CHAR), 
	"MAXPOINTINTERNALNA" VARCHAR2(75 CHAR), 
	"MAXPOINTPROMOPROGN" VARCHAR2(50 CHAR), 
	"MAXPOINTPROMOPR_BI" VARCHAR2(15 CHAR), 
	"MAXPOINTPROMOPR_BU" VARCHAR2(100 CHAR), 
	"MAX_POINTPROMONAME" VARCHAR2(50 CHAR), 
	"MAX_POINT_OBJECTCD" VARCHAR2(30 CHAR), 
	"MAX_POINT_PROGNAME" VARCHAR2(50 CHAR), 
	"MAX_POINT_PROG_BI" VARCHAR2(15 CHAR), 
	"MAX_POINT_PROG_BU" VARCHAR2(100 CHAR), 
	"MAX_POINT_PROMO_BI" VARCHAR2(15 CHAR), 
	"MAX_POINT_PROMO_BU" VARCHAR2(100 CHAR), 
	"MAX_POINT_STAT_CD" VARCHAR2(30 CHAR), 
	"MEMBER_MEM_KEY_NUM" VARCHAR2(30 CHAR), 
	"MEMSHIPPRODVENNAME" VARCHAR2(100 CHAR), 
	"MEMSHIP_PRODVENLOC" VARCHAR2(50 CHAR), 
	"MEMSHIP_PRODVEN_BI" VARCHAR2(15 CHAR), 
	"MEMSHIP_PRODVEN_BU" VARCHAR2(100 CHAR), 
	"MEMSHIP_PROD_BI" VARCHAR2(15 CHAR), 
	"MEMSHIP_PROD_BU" VARCHAR2(100 CHAR), 
	"MEMSHIP_PROD_NAME" VARCHAR2(100 CHAR), 
	"MEM_CLASS_CD" VARCHAR2(30 CHAR), 
	"MEM_GRP_CD" VARCHAR2(30 CHAR), 
	"MEM_PHASE_CD" VARCHAR2(30 CHAR), 
	"MEM_TYPE_CD" VARCHAR2(30 CHAR), 
	"NAME" VARCHAR2(100 CHAR), 
	"ORG_GRP_BI" VARCHAR2(15 CHAR), 
	"ORG_GRP_BU" VARCHAR2(100 CHAR), 
	"PAR_MEM_MEM_BI" VARCHAR2(15 CHAR), 
	"PAR_MEM_MEM_BU" VARCHAR2(100 CHAR), 
	"PAR_MEM_NUM" VARCHAR2(30 CHAR), 
	"PAR_PROG_BI" VARCHAR2(15 CHAR), 
	"PAR_PROG_BU" VARCHAR2(100 CHAR), 
	"PAR_PROG_NAME" VARCHAR2(50 CHAR), 
	"PERSON_UID" VARCHAR2(100 CHAR), 
	"PNR_NAME" VARCHAR2(26 CHAR), 
	"PPG_DESC_TEXT" VARCHAR2(250 CHAR), 
	"PPG_MEMBER_NUM" VARCHAR2(50 CHAR), 
	"PPG_OU_ACCNT_BI" VARCHAR2(15 CHAR), 
	"PPG_OU_ACCNT_BU" VARCHAR2(100 CHAR), 
	"PPG_OU_ACCNT_LOC" VARCHAR2(50 CHAR), 
	"PPG_OU_ACCNT_NAME" VARCHAR2(100 CHAR), 
	"PPG_PROG_BI" VARCHAR2(15 CHAR), 
	"PPG_PROG_BU" VARCHAR2(100 CHAR), 
	"PPG_PROG_NAME" VARCHAR2(50 CHAR), 
	"PREF_COMM_METH_CD" VARCHAR2(30 CHAR), 
	"PROGRAM_PROG_BI" VARCHAR2(15 CHAR), 
	"PROGRAM_PROG_BU" VARCHAR2(100 CHAR), 
	"PROGRAM_PROG_NAME" VARCHAR2(50 CHAR), 
	"PR_ADDR_NAME" VARCHAR2(100 CHAR), 
	"PSTN_POSTN_BI" VARCHAR2(15 CHAR), 
	"PSTN_POSTN_BU" VARCHAR2(100 CHAR), 
	"PSTN_POSTN_DIVN" VARCHAR2(100 CHAR), 
	"PSTN_POSTN_LOC" VARCHAR2(50 CHAR), 
	"PSTN_POSTN_NAME" VARCHAR2(50 CHAR), 
	"PTNR_ACCNT_BI" VARCHAR2(15 CHAR), 
	"PTNR_ACCNT_BU" VARCHAR2(100 CHAR), 
	"PTNR_ACCNT_LOC" VARCHAR2(50 CHAR), 
	"PTNR_ACCNT_NAME" VARCHAR2(100 CHAR), 
	"REFERRED_MEM_BI" VARCHAR2(15 CHAR), 
	"REFERRED_MEM_BU" VARCHAR2(100 CHAR), 
	"REFERRED_MEM_NUM" VARCHAR2(30 CHAR), 
	"REFERRED_PROG_BI" VARCHAR2(15 CHAR), 
	"REFERRED_PROG_BU" VARCHAR2(100 CHAR), 
	"REFERRED_PROG_NAME" VARCHAR2(50 CHAR), 
	"REG_CHANNEL_CD" VARCHAR2(30 CHAR), 
	"ROOT_MEM_BI" VARCHAR2(15 CHAR), 
	"ROOT_MEM_BU" VARCHAR2(100 CHAR), 
	"ROOT_MEM_NUM" VARCHAR2(30 CHAR), 
	"ROOT_PROG_BI" VARCHAR2(15 CHAR), 
	"ROOT_PROG_BU" VARCHAR2(100 CHAR), 
	"ROOT_PROG_NAME" VARCHAR2(50 CHAR), 
	"STATUS_CD" VARCHAR2(30 CHAR), 
	"STMT_MTHD_CD" VARCHAR2(30 CHAR), 
	"STMT_TYPE_CD" VARCHAR2(30 CHAR), 
	"SUBMITTOLOGINDOMAI" VARCHAR2(50 CHAR), 
	"SUBMIT_TO_LOGIN" VARCHAR2(50 CHAR), 
	"SURV_MEM_BI" VARCHAR2(15 CHAR), 
	"SURV_MEM_BU" VARCHAR2(100 CHAR), 
	"SURV_MEM_NUM" VARCHAR2(30 CHAR), 
	"SURV_PROG_BI" VARCHAR2(15 CHAR), 
	"SURV_PROG_BU" VARCHAR2(100 CHAR), 
	"SURV_PROG_NAME" VARCHAR2(50 CHAR), 
	"TIERAPPLDPROMOPROM" VARCHAR2(50 CHAR), 
	"TIERPROCESSINGCOMM" VARCHAR2(1000 CHAR), 
	"TIERPROCESSINGSTAT" VARCHAR2(30 CHAR), 
	"TIER_APPLDPROMOB_BI" VARCHAR2(15 CHAR), 
	"TIER_APPLDPROMOB_BU" VARCHAR2(100 CHAR), 
	"TIER_APPLDPROMOPRO" VARCHAR2(50 CHAR), 
	"TIER_APPLDPROMORLN" VARCHAR2(50 CHAR), 
	"TIER_APPLDPROMO_BI" VARCHAR2(15 CHAR), 
	"TIER_APPLDPROMO_BU" VARCHAR2(100 CHAR), 
	"TIER_APPLIEDPROB_BI" VARCHAR2(15 CHAR), 
	"TIER_APPLIEDPROB_BU" VARCHAR2(100 CHAR), 
	"TIER_APPLIEDPROGNA" VARCHAR2(50 CHAR), 
	"TIER_APPLIEDPROMON" VARCHAR2(50 CHAR), 
	"TIER_APPLIEDPRO_BI" VARCHAR2(15 CHAR), 
	"TIER_APPLIEDPRO_BU" VARCHAR2(100 CHAR), 
	"TIER_APPR_STAT_CD" VARCHAR2(30 CHAR), 
	"TIER_BILKBLKADP_BI" VARCHAR2(15 CHAR), 
	"TIER_BILKPROGRAMID" VARCHAR2(15 CHAR), 
	"TIER_BULKBLKADPROG" VARCHAR2(50 CHAR), 
	"TIER_BULKBLKADP_BI" VARCHAR2(15 CHAR), 
	"TIER_BULKBLKADP_BU" VARCHAR2(100 CHAR), 
	"TIER_BULKPROGRAMID" VARCHAR2(100 CHAR), 
	"TIER_CLS_NAME" VARCHAR2(30 CHAR), 
	"TIER_CLS_PROG_BI" VARCHAR2(15 CHAR), 
	"TIER_CLS_PROG_BU" VARCHAR2(100 CHAR), 
	"TIER_CLS_PROG_NAME" VARCHAR2(50 CHAR), 
	"TIER_COMMENTS" VARCHAR2(250 CHAR), 
	"TIER_FUTRTIERCLSNA" VARCHAR2(30 CHAR), 
	"TIER_FUTR_PROGNAME" VARCHAR2(50 CHAR), 
	"TIER_FUTR_PROG_BI" VARCHAR2(15 CHAR), 
	"TIER_FUTR_PROG_BU" VARCHAR2(100 CHAR), 
	"TIER_FUTR_TIERNAME" VARCHAR2(30 CHAR), 
	"TIER_LWSTDEMPROGNA" VARCHAR2(50 CHAR), 
	"TIER_LWSTDEMPRO_BI" VARCHAR2(15 CHAR), 
	"TIER_LWSTDEMPRO_BU" VARCHAR2(100 CHAR), 
	"TIER_LWSTDEMTIERCL" VARCHAR2(30 CHAR), 
	"TIER_LWSTDEMTIERNA" VARCHAR2(30 CHAR), 
	"TIER_MEM_TIER_NUM" VARCHAR2(30 CHAR), 
	"TIER_PROCESSINGLOG" VARCHAR2(1000 CHAR), 
	"TIER_SUBMITLOGINDO" VARCHAR2(50 CHAR), 
	"TIER_SUBMIT_LOGIN" VARCHAR2(50 CHAR), 
	"TIER_TIER_NAME" VARCHAR2(30 CHAR), 
	"TIER_TRCLS_NAME" VARCHAR2(30 CHAR), 
	"TIER_TRCLS_PRGNM" VARCHAR2(50 CHAR), 
	"TIER_TRCLS_PRG_BI" VARCHAR2(15 CHAR), 
	"TIER_TRCLS_PRG_BU" VARCHAR2(100 CHAR), 
	"TIER_TXN_BI" VARCHAR2(15 CHAR), 
	"TIER_TXN_BU" VARCHAR2(100 CHAR), 
	"TIER_TXN_NUM" VARCHAR2(30 CHAR), 
	"T_DELETED_ROW_ID" VARCHAR2(15 CHAR), 
	"T_EXPORTED_ROW_ID" VARCHAR2(15 CHAR), 
	"T_LOYATTRIB_ATTRIB" VARCHAR2(15 CHAR), 
	"T_LOYATTRIB_MEMBER" VARCHAR2(15 CHAR), 
	"T_LOYATTRIB__RID" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_ACCNTI" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_ACCRUA" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_APPRBY" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_BU_ID" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_CONTAC" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_LSTSTM" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_MAXPOI" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_MEMBER" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_MEMSHI" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_ORGGRO" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_PARMEM" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_PRADDR" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_PROGRA" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_PTNRSO" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_REFERR" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_ROOTME" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_SUBMIT" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER_SURVME" VARCHAR2(15 CHAR), 
	"T_LOYMEMBER__RID" VARCHAR2(15 CHAR), 
	"T_LOYMEMCON_MEMBER" VARCHAR2(15 CHAR), 
	"T_LOYMEMCON_PER_ID" VARCHAR2(15 CHAR), 
	"T_LOYMEMCON__RID" VARCHAR2(15 CHAR), 
	"T_LOYMEMPST_MEMBER" VARCHAR2(15 CHAR), 
	"T_LOYMEMPST_POSTNI" VARCHAR2(15 CHAR), 
	"T_LOYMEMPST__RID" VARCHAR2(15 CHAR), 
	"T_LOYMEMPTR_MEMBER" VARCHAR2(15 CHAR), 
	"T_LOYMEMPTR_OU_ID" VARCHAR2(15 CHAR), 
	"T_LOYMEMPTR_PROGID" VARCHAR2(15 CHAR), 
	"T_LOYMEMPTR__RID" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE_APPLDP" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE_APPLIE" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE_BULKRE" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE_FUTRTI" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE_LWSTDE" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE_MEMBER" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE_SUBMIT" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE_TIERCL" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE_TIERID" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE_TXN_ID" VARCHAR2(15 CHAR), 
	"T_LOYMEMTIE__RID" VARCHAR2(15 CHAR), 
	"T_LOYMEM_BU_BU_ID" VARCHAR2(15 CHAR), 
	"T_LOYMEM_BU_MEMBER" VARCHAR2(15 CHAR), 
	"T_LOYMEM_BU__RID" VARCHAR2(15 CHAR), 
	"T_LOY_CARD_MEMBER" VARCHAR2(15 CHAR), 
	"T_LOY_CARD_TIERID" VARCHAR2(15 CHAR), 
	"T_LOY_CARD__RID" VARCHAR2(15 CHAR), 
	"T_MERGED_ROW_ID" VARCHAR2(15 CHAR), 
	"T_TIER_BULK_REF_ID" VARCHAR2(15 CHAR), 
	"VAL_LIFE_SCORE" VARCHAR2(50 CHAR), 
	"VAL_SCORE" VARCHAR2(50 CHAR), 
	"VIS_BI" VARCHAR2(15 CHAR), 
	"VIS_BU" VARCHAR2(100 CHAR), 
	"FILE_ID" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 20 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_U1
--------------------------------------------------------

  CREATE UNIQUE INDEX "POR"."EIM_LOY_MEMBER_U1" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "ROW_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T01
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T01" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_DELETED_ROW_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T02
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T02" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_MERGED_ROW_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T03
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T03" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEMBER__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T04
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T04" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "MEM_NUM", "T_LOYMEMBER_PROGRA", "T_LOYMEMBER_BU_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T05
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T05" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "MEM_NUM", "PROGRAM_PROG_BI", "PROGRAM_PROG_NAME", "LOY_MEMBER_BI") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T06
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T06" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYATTRIB__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T07
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T07" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYATTRIB_MEMBER", "T_LOYATTRIB_ATTRIB") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T08
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T08" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOY_CARD__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T09
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T09" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEMPTR__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T10
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T10" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEMPTR_MEMBER", "T_LOYMEMPTR_PROGID", "PPG_MEMBER_NUM") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T11
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T11" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEM_BU__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T12
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T12" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEM_BU_MEMBER", "T_LOYMEM_BU_BU_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T13
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T13" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEMCON__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T14
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T14" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEMCON_MEMBER", "T_LOYMEMCON_PER_ID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T15
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T15" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEMPST__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T16
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T16" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEMPST_MEMBER", "T_LOYMEMPST_POSTNI") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T17
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T17" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEMTIE__RID") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EIM_LOY_MEMBER_T18
--------------------------------------------------------

  CREATE INDEX "POR"."EIM_LOY_MEMBER_T18" ON "POR"."EIM_LOY_MEMBER" ("IF_ROW_BATCH_NUM", "T_LOYMEMTIE_MEMBER", "T_LOYMEMTIE_TIERCL", "TIER_SEQ_NUM") 
  PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EIM_LOY_MEMBER
--------------------------------------------------------

  ALTER TABLE "POR"."EIM_LOY_MEMBER" MODIFY ("MEM_NUM" NOT NULL ENABLE);
  ALTER TABLE "POR"."EIM_LOY_MEMBER" MODIFY ("IF_ROW_STAT" NOT NULL ENABLE);
  ALTER TABLE "POR"."EIM_LOY_MEMBER" MODIFY ("IF_ROW_BATCH_NUM" NOT NULL ENABLE);
  ALTER TABLE "POR"."EIM_LOY_MEMBER" MODIFY ("ROW_ID" NOT NULL ENABLE);

