--------------------------------------------------------
--  File created - Monday-August-27-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CX_FINT_ERROR
--------------------------------------------------------

  CREATE TABLE "SIEBEL"."CX_FINT_ERROR" 
   (	"ROW_ID" VARCHAR2(15 CHAR), 
	"CREATED" DATE DEFAULT sysdate, 
	"CREATED_BY" VARCHAR2(15 CHAR), 
	"LAST_UPD" DATE DEFAULT sysdate, 
	"LAST_UPD_BY" VARCHAR2(15 CHAR), 
	"MODIFICATION_NUM" NUMBER(10,0) DEFAULT 0, 
	"CONFLICT_ID" VARCHAR2(15 CHAR) DEFAULT '0', 
	"DB_LAST_UPD" DATE, 
	"SYSTEM" CHAR(1 CHAR), 
	"DB_LAST_UPD_SRC" VARCHAR2(50 CHAR), 
	"ERROR_CD" VARCHAR2(30 CHAR), 
	"ERROR_DESC" VARCHAR2(250 CHAR), 
	"PRTNR_ERROR_CD" VARCHAR2(30 CHAR), 
	"PRTNR_ERROR_DESC" VARCHAR2(250 CHAR), 
	"SOURCE" VARCHAR2(30 CHAR), 
	"SBL_ENTITY" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CX_FINT_ERROR
--------------------------------------------------------

  ALTER TABLE "SIEBEL"."CX_FINT_ERROR" MODIFY ("CONFLICT_ID" NOT NULL ENABLE);
  ALTER TABLE "SIEBEL"."CX_FINT_ERROR" MODIFY ("MODIFICATION_NUM" NOT NULL ENABLE);
  ALTER TABLE "SIEBEL"."CX_FINT_ERROR" MODIFY ("LAST_UPD_BY" NOT NULL ENABLE);
  ALTER TABLE "SIEBEL"."CX_FINT_ERROR" MODIFY ("LAST_UPD" NOT NULL ENABLE);
  ALTER TABLE "SIEBEL"."CX_FINT_ERROR" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SIEBEL"."CX_FINT_ERROR" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SIEBEL"."CX_FINT_ERROR" MODIFY ("ROW_ID" NOT NULL ENABLE);

