WHENEVER SQLERROR EXIT 1;

DECLARE
	POINTS NUMBER;
	CALC_POINTS NUMBER;

BEGIN
	 SELECT FILE_POINTS INTO POINTS
	   FROM SIEBEL.CX_FINT_FILE
		WHERE ROW_ID = '&1';

		SELECT SUM(NUM_POINTS) INTO CALC_POINTS
		  FROM SIEBEL.CX_FINT_TXN 
		 WHERE FILE_ID = '&1';

		IF POINTS <> CALC_POINTS THEN
			RAISE_APPLICATION_ERROR(-20000,'Points in file header ('||POINTS||') do not match sum of points in file ('||CALC_POINTS||')');
		END IF;
END;
/
quit
/
