ALTER TABLE &1..EIM_LOY_TXN ADD ( FILE_ID VARCHAR2(15) );
ALTER TABLE &1..EIM_LOY_MEMBER ADD ( FILE_ID VARCHAR2(15) );

CREATE INDEX &1..FX_EIM_LOY_TXN_F1 ON SIEBEL.EIM_LOY_TXN (
	FILE_ID
);

CREATE INDEX &1..FX_EIM_LOY_MEMBER_F1 ON SIEBEL.EIM_LOY_MEMBER (
	FILE_ID
);
QUIT
/
