DROP SYNONYM TO_62BASE ;
DROP SYNONYM LM_ROWID_SEQ ;
DROP SYNONYM LM_EIM_SEQ ;
DROP SYNONYM LM_GEN_UID ;
DROP SYNONYM LM_ERROR ;
CREATE SYNONYM TO_62BASE FOR &1..TO_62BASE;
CREATE SYNONYM LM_ROWID_SEQ FOR &1..LM_ROWID_SEQ;
CREATE SYNONYM LM_EIM_SEQ FOR &1..LM_EIM_SEQ;
CREATE SYNONYM LM_GEN_UID FOR &1..LM_GEN_UID;
CREATE SYNONYM LM_ERROR FOR &1..LM_ERROR;
quit
/
