------- CHECK TRANSACTION MEMBERS ------

DECLARE
  IN_FILE_ID VARCHAR2(15) := :FILE_ID;
  IN_PROG_NAME VARCHAR(100) := :PROG_NAME;

  TYPE T_ROW_ID IS TABLE OF VARCHAR2( 15);
  TYPE T_MEM_NUM IS TABLE OF VARCHAR2( 30);
  TYPE T_PROG_NAME IS TABLE OF VARCHAR2( 50);
  TYPE T_MEMBER_MEM_NUM IS TABLE OF VARCHAR2( 250);

  V_ROW_ID T_ROW_ID;
  V_MEM_NUM T_MEM_NUM;
  V_PROG_NAME T_PROG_NAME;
  V_MEMBER_MEM_NUM T_MEMBER_MEM_NUM;

  CURSOR C_MEMBERS IS
   SELECT ROW_ID, MEM_NUM, PROG_NAME, MEMBER_MEM_NUM                                            
        FROM (
      SELECT SBL_MEM.ROW_ID ROW_ID, SBL_MEM.MEM_NUM MEM_NUM, SBL_PROG.NAME PROG_NAME, STG_TXN._LM_<MemberNumberColumn> MEMBER_MEM_NUM
	      FROM SIEBEL._LM_<PrestageTable> STG_TXN
	      LEFT OUTER JOIN SIEBEL.S_LOY_MEMBER SBL_MEM ON (STG_TXN._LM_<MemberNumberColumn> = SBL_MEM.MEM_NUM AND SBL_MEM.STATUS_CD IN ( _LM_<MemberStatusList> ))
	      LEFT OUTER JOIN SIEBEL.S_LOY_PROGRAM SBL_PROG ON (SBL_MEM.PROGRAM_ID = SBL_PROG.ROW_ID AND SBL_PROG.NAME = IN_PROG_NAME)
       WHERE
      STG_TXN.REC_STATUS = 'Prestaged' AND STG_TXN.FILE_ID = IN_FILE_ID AND MEM_NUM IS NULL );

	BEGIN
         OPEN C_MEMBERS;

         LOOP
            FETCH C_MEMBERS BULK COLLECT INTO V_ROW_ID, V_MEM_NUM, V_PROG_NAME, V_MEMBER_MEM_NUM LIMIT 500;
            EXIT WHEN V_ROW_ID.COUNT() = 0;

            FORALL i IN V_ROW_ID.FIRST..V_ROW_ID.LAST
             UPDATE SIEBEL._LM_<PrestageTable>
                SET
	             ERROR_CODE = 'SBL-FINT-0007',
	             ERROR_DESC = LM_ERROR('SBL-FINT-0007',V_MEMBER_MEM_NUM(i)),
	             REC_STATUS = 'Error'
             WHERE _LM_<MemberNumberColumn> = V_MEMBER_MEM_NUM(i) AND FILE_ID = IN_FILE_ID;
        COMMIT;
    END LOOP;
END;
